### ISSUE TITLE
Differences between guide and code

### ISSUE THREAD

**Issue by kumaheiyama** [tpeczek/Demo.AspNetCore.Angular.PushNotifications#13]
Hi,

Thanks for an excellent guide!
However, there are a few issues with the guide versus the complete code. My suggestion is to update the guide so it will work even if a read doesn't go into the complete code.

1. I think you need to specify which version of LiteDb to use. It seems that the latest version (5.0.8) doesn't implement LiteCollection but ILiteCollection. Version 4.1.4 has seems to be working but I haven't had time to check it fully.
    * So the following initiation doesn't work `_collection = _liteDatabase.GetCollection<LitePushSubscription>("subscriptions");` as it can't convert between ILiteCollection and LiteCollection.
    * Also the new version doesn't use the same signature for Delete so I can't get `_collection.Delete(sub => sub.Endpoint == endpoint);` to work. The new version requires a BsonValue and doesn't accept a string.
    * I would suggest either specifying which version of LiteDb to use or update the code for version 5.*.
1. There are a few key code snippets missing from the guide:
    * LitePushSubscription isn't anywhere in the guide.
    * The service configurations (AddSingleton, AddHttpClient, AddHostedService) aren't in the guide.
1. The PushSubscriptionsController in the guide does not match the complete code as it doesn't use WebUtility.
1. In pushsubscriber.component.ts the readonly httpOptions is missing from the guide, which doesn't compile.

/K

**Comment by tpeczek** [comment]
Hi @kumaheiyama,

The goal of the article (I'm assuming you are referring to this one --> https://www.telerik.com/blogs/push-notifications-in-asp-net-core-with-angular) is not to specify every single detail, only the key aspects. This is why it is accompanied by this demo project which contains all the less important details.

As you have noticed, the code snippets have been limited only to key aspects. The absence of code is indicated and article points to this project.

This project also clearly specifies versions of all the dependencies through the .csproj file (for example version 5 of LiteDb didn't event existed when all those resources were created). Updating the demo project to the current version would be an option, but first of all it requires significant amount of time and my resources are limited, so I allocate them were there is most interest. Updating the demo would also made it less compatible with article which I have no way of updating as I'm not the owner.

**Comment by kumaheiyama** [comment]
Hi,

Thanks for clarifying! If you have no way of updating the article there isn't much to do.
My point was that following the article (to a tee) would result in non functioning code as versions have moved on from when you wrote the article. There is no mention of versions in the article and without deep diving into the github link one could easily miss these kind of things.

I agree that there is no point updating to v5, as that would make the code move away from article.

Thanks again for an excellent article, and I hope this was received only as constructive criticism.

**Comment by tpeczek** [comment]
Thank you, this was a constructive feedback. I'm sorry I couldn't do anything more on this.
