### ISSUE TITLE
Question: Why the need to ng build --prod?

### ISSUE THREAD

**Issue by omatrot** [tpeczek/Demo.AspNetCore.Angular.PushNotifications#8]
I've noticed that during the build of the project, there is an additional step to ng build --prod.
Could you explain why it is needed?
What are the steps to manually edit the project file to do so?
Thanks in advance.

**Comment by tpeczek** [comment]
This is required for Angular to deploy its service worker. By default  ASP.NET Core is using `ng serve` but in such case Angular doesn't deploy its service worker.

You can read more here: https://www.telerik.com/blogs/push-notifications-in-asp-net-core-with-angular#adding-angular-service-worker (this demo has been created together with that article).

**Comment by omatrot** [comment]
Does this means that we can't debug TS code?

**Comment by tpeczek** [comment]
It means it's complicated :). You can switch between `ng serve` and `ng build --prod` depending if you want debuging or service worker. The true problem is when you want to debug the service code - your only option for that is debuging prod code in browser.

**Comment by omatrot** [comment]
I see.
The problem is that I'm trying to understand why Service Worker [does not work](https://github.com/angular/angular/issues/29067) in my existing site, while working in a fresh one.

**Comment by tpeczek** [comment]
I'm afraid I don't have the answer you are looking for.

**Comment by omatrot** [comment]
Thanks anyway.
